name: CI - GridWatch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check FastAPI app runs
      run: |
        uvicorn src.app:app --host 0.0.0.0 --port 8000 &
        sleep 5
        curl --fail http://localhost:8000 || exit 1

    - name: Test Docker build
      run: |
        docker build -t gridwatch-app .
